export const mockInventory = [
  {
    id: 1,
    brand: "Tesla",
    model: "Model S Plaid",
    category: "EV",
    price: 89990,
    status: "Available",
    mileage: 0,
    image: "https://loremflickr.com/800/600/tesla?lock=1",
    logo: "https://cdn.brandfetch.io/tesla.com/w/400/h/400",
    year: 2023,
    serviceHistory: ["Pre-delivery inspection", "Battery check"],
  },
  {
    id: 2,
    brand: "Porsche",
    model: "911 Carrera",
    category: "Luxury",
    price: 114400,
    status: "Reserved",
    mileage: 120,
    image: "https://loremflickr.com/800/600/porsche,911?lock=1",
    logo: "https://cdn.brandfetch.io/porsche.com/w/400/h/400",
    year: 2023,
    serviceHistory: ["PDI", "Detailing"],
  },
  {
    id: 3,
    brand: "Audi",
    model: "e-tron GT",
    category: "EV",
    price: 104900,
    status: "In Transit",
    mileage: 0,
    image: "https://loremflickr.com/800/600/audi?lock=1",
    logo: "https://cdn.brandfetch.io/audi.com/w/400/h/400",
    year: 2024,
    serviceHistory: [],
  },
  {
    id: 4,
    brand: "Mercedes-Benz",
    model: "G-Class AMG",
    category: "SUV",
    price: 139900,
    status: "Available",
    mileage: 500,
    image: "https://loremflickr.com/800/600/mercedes?lock=1",
    logo: "https://cdn.brandfetch.io/mercedes-benz.com/w/400/h/400",
    year: 2022,
    serviceHistory: ["A-Service", "B-Service"],
  },
  {
    id: 5,
    brand: "BMW",
    model: "X7 M60i",
    category: "SUV",
    price: 103100,
    status: "Sold",
    mileage: 50,
    image: "https://loremflickr.com/800/600/bmw,suv?lock=1",
    logo: "https://cdn.brandfetch.io/bmw.com/w/400/h/400",
    year: 2023,
    serviceHistory: ["Delivery prep"],
  },
  {
    id: 6,
    brand: "Lucid",
    model: "Air Grand Touring",
    category: "EV",
    price: 138000,
    status: "Available",
    mileage: 10,
    image: "https://loremflickr.com/800/600/car,electric?lock=2",
    logo: "https://cdn.brandfetch.io/lucidmotors.com/w/400/h/400",
    year: 2024,
    serviceHistory: ["Software Update"],
  },
  {
    id: 7,
    brand: "Range Rover",
    model: "Autobiography",
    category: "Luxury",
    price: 141100,
    status: "Available",
    mileage: 25,
    image: "https://loremflickr.com/800/600/rangerover?lock=1",
    logo: "https://cdn.brandfetch.io/landrover.com/w/400/h/400",
    year: 2023,
    serviceHistory: ["PDI"],
  },
  {
    id: 8,
    brand: "Aston Martin",
    model: "DBX",
    category: "SUV",
    price: 185900,
    status: "Reserved",
    mileage: 300,
    image: "https://loremflickr.com/800/600/astonmartin?lock=1",
    logo: "https://cdn.brandfetch.io/astonmartin.com/w/400/h/400",
    year: 2022,
    serviceHistory: ["Annual service"],
  },
  {
    id: 9,
    brand: "Rivian",
    model: "R1S",
    category: "EV",
    price: 78000,
    status: "In Transit",
    mileage: 0,
    image: "https://loremflickr.com/800/600/suv,electric?lock=3",
    logo: "https://cdn.brandfetch.io/rivian.com/w/400/h/400",
    year: 2024,
    serviceHistory: [],
  },
  {
    id: 10,
    brand: "Bentley",
    model: "Continental GT",
    category: "Luxury",
    price: 235500,
    status: "Available",
    mileage: 800,
    image: "https://loremflickr.com/800/600/bentley?lock=1",
    logo: "https://cdn.brandfetch.io/bentleymotors.com/w/400/h/400",
    year: 2021,
    serviceHistory: ["1000m Check"],
  },
  {
    id: 11,
    brand: "Lexus",
    model: "RX 500h",
    category: "SUV",
    price: 63800,
    status: "Sold",
    mileage: 1200,
    image: "https://loremflickr.com/800/600/lexus?lock=1",
    logo: "https://cdn.brandfetch.io/lexus.com/w/400/h/400",
    year: 2023,
    serviceHistory: ["First Service"],
  },
  {
    id: 12,
    brand: "Genesis",
    model: "G90",
    category: "Luxury",
    price: 88400,
    status: "Available",
    mileage: 15,
    image: "https://loremflickr.com/800/600/genesis,car?lock=1",
    logo: "https://cdn.brandfetch.io/genesis.com/w/400/h/400",
    year: 2023,
    serviceHistory: ["PDI"],
  },
  {
    id: 13,
    brand: "Polestar",
    model: "3",
    category: "EV",
    price: 83900,
    status: "In Transit",
    mileage: 0,
    image: "https://loremflickr.com/800/600/polestar?lock=1",
    logo: "https://cdn.brandfetch.io/polestar.com/w/400/h/400",
    year: 2024,
    serviceHistory: [],
  },
  {
    id: 14,
    brand: "Porsche",
    model: "Taycan 4S",
    category: "EV",
    price: 106500,
    status: "Reserved",
    mileage: 450,
    image: "https://loremflickr.com/800/600/taycan?lock=1",
    logo: "https://cdn.brandfetch.io/porsche.com/w/400/h/400",
    year: 2022,
    serviceHistory: ["Battery Health Check"],
  },
  {
    id: 15,
    brand: "Rolls-Royce",
    model: "Cullinan",
    category: "Luxury",
    price: 348500,
    status: "Available",
    mileage: 100,
    image: "https://loremflickr.com/800/600/rollsroyce?lock=1",
    logo: "https://cdn.brandfetch.io/rolls-roycemotorcars.com/w/400/h/400",
    year: 2023,
    serviceHistory: ["Bespoke detailing"],
  },
];

export const mockStats = {
  totalVehicles: 45,
  available: 28,
  soldThisMonth: 12,
  revenue: 2540000,
};

export const chartData = [
  { name: "Week 1", stock: 50, sales: 5 },
  { name: "Week 2", stock: 48, sales: 8 },
  { name: "Week 3", stock: 45, sales: 4 },
  { name: "Week 4", stock: 45, sales: 12 },
];
